# File: .github/workflows/libusb.yml

on:
  schedule:
  - cron:  "*/15 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    env:
      SOURCE_REPO: "https://github.com/libusb/libusb.git"
      DEST_REPO: "https://${{ github.actor }}:${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}@github.com/saschazepter/libusb.git"
      REPO_PREFIX: ""
    steps:
    #- uses: actions/checkout@v4
    #  with:
    #    persist-credentials: false
    - run: |
        #sudo add-apt-repository -y "ppa:git-core/ppa"
        #sudo apt-get update
        #sudo apt-get -y install git-filter-repo
        #curl https://raw.githubusercontent.com/mnauw/git-remote-hg/refs/tags/v1.0.3.2/git-remote-hg --no-progress-meter --create-dirs -o ~/.local/bin/git-remote-hg
        #chmod +x ~/.local/bin/git-remote-hg; sed -i -e "s/re.\(compile\|match\)(b'/re.\1(br'/g" ~/.local/bin/git-remote-hg

        git clone --mirror "$SOURCE_REPO" .
        git config --unset-all remote.origin.mirror || :
        git for-each-ref --format 'delete %(refname)' refs/pull | git update-ref --stdin

        git config --unset-all http."https://github.com/".extraheader || :

        echo "Resetting origin to: $DEST_REPO"
        git remote set-url origin "$DEST_REPO"

        echo "Adding tmp_upstream $SOURCE_REPO"
        git remote add tmp_upstream "$SOURCE_REPO"

        echo "Fetching tmp_upstream"
        git fetch tmp_upstream --quiet
        git remote --verbose

        echo "Pushing changings from tmp_upstream to origin"
        for branch in $(git for-each-ref --format='%(refname:short)' refs/heads | sed -e 's|heads/||g'); do
          git branch -M "${branch}" "${REPO_PREFIX}${branch}";
        done; git push origin --all --force; git push origin "*:*" --force

        echo "Force syncing all tags"
        #for tag in $(git tag -l); do
        #  git tag "${REPO_PREFIX}${tag}" "${tag}^{}" 2> /dev/null && git tag -d "${tag}";
        #done;
        git push origin --tags --force

        echo "Removing tmp_upstream"
        git remote rm tmp_upstream
        git remote --verbose 
